export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";
export const FETCH_COMMENTS_SUCCES = "FETCH_COMMENTS_SUCCES";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMETNS_FAIL";

export const POST_COMMENT = "POST_COMMENT";
