export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_START = "FETCH_COMMENTS_START";
export const FETCH_COMMENTS_SUCCES = "FETCH_COMMENTS_SUCCES";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMETNS_FAIL";

export const POST_COMMENT_START = "POST_COMMENT_START";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAIL = "POST_COMMENT_FAIL";
